{% set name = "azure-mgmt-redis" %}
{% set version = "14.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 584acd4228a79b104dc9a380a9b1d61a4d8e2f1b4cf68eb7c0311019ffa22fa4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common ~=1.1

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.redis

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Management Redis Library for Python.

extra:
  recipe-maintainers:
    - tim-werner
