{% set name = "azure-mgmt-redis" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: db999e104edeee3a13a8ceb1881e15196fe03a02635e0e20855eb52c1e2ecca1

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common ~=1.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.redis

about:
  home:  https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Management Redis Library for Python.

extra:
  recipe-maintainers:
    - tim-werner
