schema_version: 1

context:
  name: azure-mgmt-redis
  version: 6.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.zip
  sha256: db999e104edeee3a13a8ceb1881e15196fe03a02635e0e20855eb52c1e2ecca1

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - azure-common ~=1.1

tests:
  - python:
      imports:
        - azure
        - azure.mgmt
        - azure.mgmt.redis
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE.txt
  summary: Microsoft Azure Management Redis Library for Python.
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - tim-werner
    - janjagusch
